image: admindptinfo/dc:terra

variables:
  VAULT_SERVER_URL: https://vault-dc.info.univ-lyon1.fr
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/tfstate
cache:
  key: example-production
  paths:
    - ${TF_ROOT}/.terraform
before_script:
  - cd ${TF_ROOT}
stages:
  - prepare
  - validate
  - build
  - deploy
  - cleanup

init:
  stage: prepare
  script:
    - gitlab-terraform init
validate:
  stage: validate
  script:
    - gitlab-terraform validate
plan:
  stage: build
  script:
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=gitlab-ci jwt=$CI_JOB_JWT)"
    - export OS_APPLICATION_CREDENTIAL_SECRET=$(vault kv get -field=credential kv/asbd-kevily/tp2)
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
apply:
  stage: deploy
  script:
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=gitlab-ci jwt=$CI_JOB_JWT)"
    - export OS_APPLICATION_CREDENTIAL_SECRET=$(vault kv get -field=credential kv/asbd-kevily/tp2)
    - gitlab-terraform apply
  dependencies:
    - plan
  when: manual
  only:
    - main
destroy:
  stage: cleanup
  script:
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=gitlab-ci jwt=$CI_JOB_JWT)"
    - export OS_APPLICATION_CREDENTIAL_SECRET=$(vault kv get -field=credential kv/asbd-nomgroupe/projetgitlab)
    - gitlab-terraform destroy
  resource_group: ${TF_STATE_NAME}
  when: manual
